export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: Array<{ emoji: string; name: string }>;
}

export const emojiData: EmojiCategory[] = [
  {
    name: 'Smileys & People',
    icon: 'Smile', // matches lucide-react-native icon name or can be handled in UI
    emojis: [
      { emoji: '😀', name: 'Grinning face' },
      { emoji: '😃', name: 'Grinning face with big eyes' },
      { emoji: '😄', name: 'Grinning face with smiling eyes' },
      { emoji: '😁', name: 'Beaming face with smiling eyes' },
      { emoji: '😆', name: 'Grinning squinting face' },
      { emoji: '😅', name: 'Grinning face with sweat' },
      { emoji: '🤣', name: 'Rolling on the floor laughing' },
      { emoji: '😂', name: 'Face with tears of joy' },
      { emoji: '🙂', name: 'Slightly smiling face' },
      { emoji: '🙃', name: 'Upside-down face' },
      { emoji: '😉', name: 'Winking face' },
      { emoji: '😊', name: 'Smiling face with smiling eyes' },
      { emoji: '😇', name: 'Smiling face with halo' },
      { emoji: '🥰', name: 'Smiling face with hearts' },
      { emoji: '😍', name: 'Smiling face with heart-eyes' },
      { emoji: '🤩', name: 'Star-struck' },
      { emoji: '😘', name: 'Face blowing a kiss' },
      { emoji: '😗', name: 'Kissing face' },
      { emoji: '😚', name: 'Kissing face with closed eyes' },
      { emoji: '😙', name: 'Kissing face with smiling eyes' },
      { emoji: '🥲', name: 'Smiling face with tear' },
      { emoji: '😋', name: 'Face savoring food' },
      { emoji: '😛', name: 'Face with tongue' },
      { emoji: '😜', name: 'Winking face with tongue' },
      { emoji: '🤪', name: 'Zany face' },
      { emoji: '😝', name: 'Squinting face with tongue' },
      { emoji: '🤑', name: 'Money-mouth face' },
      { emoji: '🤗', name: 'Hugging face' },
      { emoji: '🤭', name: 'Face with hand over mouth' },
      { emoji: '🤫', name: 'Shushing face' },
      { emoji: '🤔', name: 'Thinking face' },
      { emoji: '🤐', name: 'Zipper-mouth face' },
      { emoji: '🤨', name: 'Face with raised eyebrow' },
      { emoji: '😐', name: 'Neutral face' },
      { emoji: '😑', name: 'Expressionless face' },
      { emoji: '😶', name: 'Face without mouth' },
      { emoji: '😏', name: 'Smirking face' },
      { emoji: '😒', name: 'Unamused face' },
      { emoji: '🙄', name: 'Face with rolling eyes' },
      { emoji: '😬', name: 'Grimacing face' },
      { emoji: '😮‍💨', name: 'Face exhaling' },
      { emoji: '🤥', name: 'Lying face' },
      { emoji: '😌', name: 'Relieved face' },
      { emoji: '😔', name: 'Pensive face' },
      { emoji: '😪', name: 'Sleepy face' },
      { emoji: '🤤', name: 'Drooling face' },
      { emoji: '😴', name: 'Sleeping face' },
      { emoji: '😷', name: 'Face with medical mask' },
      { emoji: '🤒', name: 'Face with thermometer' },
      { emoji: '🤕', name: 'Face with head-bandage' },
      { emoji: '🤢', name: 'Nauseated face' },
      { emoji: '🤮', name: 'Face vomiting' },
      { emoji: '🤧', name: 'Sneezing face' },
      { emoji: '🥵', name: 'Hot face' },
      { emoji: '🥶', name: 'Cold face' },
      { emoji: '🥴', name: 'Woozy face' },
      { emoji: '😵', name: 'Dizzy face' },
      { emoji: '🤯', name: 'Exploding head' },
      { emoji: '🤠', name: 'Cowboy hat face' },
      { emoji: '🥳', name: 'Partying face' },
      { emoji: '🥸', name: 'Disguised face' },
      { emoji: '😎', name: 'Smiling face with sunglasses' },
      { emoji: '🤓', name: 'Nerd face' },
      { emoji: '🧐', name: 'Face with monocle' },
      { emoji: '😕', name: 'Confused face' },
      { emoji: '😟', name: 'Worried face' },
      { emoji: '🙁', name: 'Slightly frowning face' },
      { emoji: '☹️', name: 'Frowning face' },
      { emoji: '😮', name: 'Face with open mouth' },
      { emoji: '😯', name: 'Hushed face' },
      { emoji: '😲', name: 'Astonished face' },
      { emoji: '😳', name: 'Flushed face' },
      { emoji: '🥺', name: 'Pleading face' },
      { emoji: '😦', name: 'Frowning face with open mouth' },
      { emoji: '😧', name: 'Anguished face' },
      { emoji: '😨', name: 'Fearful face' },
      { emoji: '😰', name: 'Anxious face with sweat' },
      { emoji: '😥', name: 'Sad but relieved face' },
      { emoji: '😢', name: 'Crying face' },
      { emoji: '😭', name: 'Loudly crying face' },
      { emoji: '😱', name: 'Face screaming in fear' },
      { emoji: '😖', name: 'Confounded face' },
      { emoji: '😣', name: 'Persevering face' },
      { emoji: '😞', name: 'Disappointed face' },
      { emoji: '😓', name: 'Downcast face with sweat' },
      { emoji: '😩', name: 'Weary face' },
      { emoji: '😫', name: 'Tired face' },
      { emoji: '🥱', name: 'Yawning face' },
      { emoji: '😤', name: 'Face with steam from nose' },
      { emoji: '😡', name: 'Pouting face' },
      { emoji: '😠', name: 'Angry face' },
      { emoji: '🤬', name: 'Face with symbols on mouth' },
      { emoji: '😈', name: 'Smiling face with horns' },
      { emoji: '👿', name: 'Angry face with horns' },
      { emoji: '💀', name: 'Skull' },
    ],
  },
  {
    name: 'Animals & Nature',
    icon: 'Cat', // Note: placeholder icon names
    emojis: [
      { emoji: '🐶', name: 'Dog face' },
      { emoji: '🐱', name: 'Cat face' },
      { emoji: '🐭', name: 'Mouse face' },
      { emoji: '🐹', name: 'Hamster face' },
      { emoji: '🐰', name: 'Rabbit face' },
      { emoji: '🦊', name: 'Fox' },
      { emoji: '🐻', name: 'Bear' },
      { emoji: '🐼', name: 'Panda' },
      { emoji: '🐻‍❄️', name: 'Polar bear' },
      { emoji: '🐨', name: 'Koala' },
      { emoji: '🐯', name: 'Tiger face' },
      { emoji: '🦁', name: 'Lion' },
      { emoji: '🐮', name: 'Cow face' },
      { emoji: '🐷', name: 'Pig face' },
      { emoji: '🐸', name: 'Frog' },
      { emoji: '🐵', name: 'Monkey face' },
      { emoji: '🙈', name: 'See-no-evil monkey' },
      { emoji: '🙉', name: 'Hear-no-evil monkey' },
      { emoji: '🙊', name: 'Speak-no-evil monkey' },
      { emoji: '🐧', name: 'Penguin' },
      { emoji: '🐦', name: 'Bird' },
      { emoji: '🐤', name: 'Baby chick' },
      { emoji: '🦉', name: 'Owl' },
      { emoji: '🦇', name: 'Bat' },
      { emoji: '🐺', name: 'Wolf' },
      { emoji: '🦄', name: 'Unicorn' },
      { emoji: '🐝', name: 'Honeybee' },
      { emoji: '🦋', name: 'Butterfly' },
      { emoji: '🐌', name: 'Snail' },
      { emoji: '🐞', name: 'Lady beetle' },
      { emoji: '🐢', name: 'Turtle' },
      { emoji: '🐍', name: 'Snake' },
      { emoji: '🐙', name: 'Octopus' },
      { emoji: '🦑', name: 'Squid' },
      { emoji: '🦞', name: 'Lobster' },
      { emoji: '🦀', name: 'Crab' },
      { emoji: '🐳', name: 'Spouting whale' },
      { emoji: '🐬', name: 'Dolphin' },
      { emoji: '🐟', name: 'Fish' },
      { emoji: '🐠', name: 'Tropical fish' },
      { emoji: '🐡', name: 'Blowfish' },
      { emoji: '🦈', name: 'Shark' },
      { emoji: '🐊', name: 'Crocodile' },
      { emoji: '🐅', name: 'Tiger' },
      { emoji: '🐆', name: 'Leopard' },
      { emoji: '🦓', name: 'Zebra' },
      { emoji: '🦍', name: 'Gorilla' },
      { emoji: '🦧', name: 'Orangutan' },
      { emoji: '🐘', name: 'Elephant' },
      { emoji: '🦛', name: 'Hippopotamus' },
      { emoji: '🦏', name: 'Rhinoceros' },
      { emoji: '🐪', name: 'Camel' },
      { emoji: '🦒', name: 'Giraffe' },
      { emoji: '🦘', name: 'Kangaroo' },
      { emoji: '🐃', name: 'Water buffalo' },
      { emoji: '🐂', name: 'Ox' },
      { emoji: '🐄', name: 'Cow' },
      { emoji: '🐎', name: 'Horse' },
      { emoji: '🐖', name: 'Pig' },
      { emoji: '🐏', name: 'Ram' },
      { emoji: '🐑', name: 'Ewe' },
      { emoji: '🦙', name: 'Llama' },
      { emoji: '🐐', name: 'Goat' },
      { emoji: '🦌', name: 'Deer' },
      { emoji: '🐕', name: 'Dog' },
      { emoji: '🐩', name: 'Poodle' },
      { emoji: '🐈', name: 'Cat' },
      { emoji: '🐓', name: 'Rooster' },
      { emoji: '🦃', name: 'Turkey' },
      { emoji: '🦚', name: 'Peacock' },
      { emoji: '🦜', name: 'Parrot' },
      { emoji: '🦢', name: 'Swan' },
      { emoji: '🦩', name: 'Flamingo' },
      { emoji: '🕊️', name: 'Dove' },
      { emoji: '🐇', name: 'Rabbit' },
      { emoji: '🦝', name: 'Raccoon' },
      { emoji: '🦨', name: 'Skunk' },
      { emoji: '🦡', name: 'Badger' },
      { emoji: '🦦', name: 'Otter' },
      { emoji: '🦥', name: 'Sloth' },
      { emoji: '🐁', name: 'Mouse' },
      { emoji: '🐀', name: 'Rat' },
      { emoji: '🐿️', name: 'Chipmunk' },
      { emoji: '🦔', name: 'Hedgehog' },
      { emoji: '🌲', name: 'Evergreen tree' },
      { emoji: '🌳', name: 'Deciduous tree' },
      { emoji: '🌴', name: 'Palm tree' },
      { emoji: '🌵', name: 'Cactus' },
      { emoji: '🌾', name: 'Sheaf of rice' },
      { emoji: '🌿', name: 'Herb' },
      { emoji: '☘️', name: 'Shamrock' },
      { emoji: '🍀', name: 'Four leaf clover' },
      { emoji: '🍁', name: 'Maple leaf' },
      { emoji: '🍂', name: 'Fallen leaf' },
      { emoji: '🍃', name: 'Leaf fluttering in wind' },
      { emoji: '🍄', name: 'Mushroom' },
      { emoji: '🌰', name: 'Chestnut' },
      { emoji: '🌸', name: 'Cherry blossom' },
      { emoji: '🌹', name: 'Rose' },
      { emoji: '🥀', name: 'Wilted flower' },
      { emoji: '🌺', name: 'Hibiscus' },
      { emoji: '🌻', name: 'Sunflower' },
      { emoji: '🌼', name: 'Blossom' },
      { emoji: '🌷', name: 'Tulip' },
    ]
  },
  {
    name: 'Food & Drink',
    icon: 'Coffee', // Placeholder
    emojis: [
      { emoji: '🍏', name: 'Green apple' },
      { emoji: '🍎', name: 'Red apple' },
      { emoji: '🍐', name: 'Pear' },
      { emoji: '🍊', name: 'Tangerine' },
      { emoji: '🍋', name: 'Lemon' },
      { emoji: '🍌', name: 'Banana' },
      { emoji: '🍉', name: 'Watermelon' },
      { emoji: '🍇', name: 'Grapes' },
      { emoji: '🍓', name: 'Strawberry' },
      { emoji: '🫐', name: 'Blueberries' },
      { emoji: '🍈', name: 'Melon' },
      { emoji: '🍒', name: 'Cherries' },
      { emoji: '🍑', name: 'Peach' },
      { emoji: '🥭', name: 'Mango' },
      { emoji: '🍍', name: 'Pineapple' },
      { emoji: '🥥', name: 'Coconut' },
      { emoji: '🥝', name: 'Kiwi fruit' },
      { emoji: '🍅', name: 'Tomato' },
      { emoji: '🍆', name: 'Eggplant' },
      { emoji: '🥑', name: 'Avocado' },
      { emoji: '🥦', name: 'Broccoli' },
      { emoji: '🥬', name: 'Leafy green' },
      { emoji: '🥒', name: 'Cucumber' },
      { emoji: '🌶️', name: 'Hot pepper' },
      { emoji: '🫑', name: 'Bell pepper' },
      { emoji: '🌽', name: 'Ear of corn' },
      { emoji: '🥕', name: 'Carrot' },
      { emoji: '🧄', name: 'Garlic' },
      { emoji: '🧅', name: 'Onion' },
      { emoji: '🥔', name: 'Potato' },
      { emoji: '🍠', name: 'Roasted sweet potato' },
      { emoji: '🥐', name: 'Croissant' },
      { emoji: '🥯', name: 'Bagel' },
      { emoji: '🍞', name: 'Bread' },
      { emoji: '🥖', name: 'Baguette bread' },
      { emoji: '🥨', name: 'Pretzel' },
      { emoji: '🧀', name: 'Cheese wedge' },
      { emoji: '🥚', name: 'Egg' },
      { emoji: '🍳', name: 'Cooking' },
      { emoji: '🧈', name: 'Butter' },
      { emoji: '🥞', name: 'Pancakes' },
      { emoji: '🧇', name: 'Waffle' },
      { emoji: '🥓', name: 'Bacon' },
      { emoji: '🥩', name: 'Cut of meat' },
      { emoji: '🍗', name: 'Poultry leg' },
      { emoji: '🍖', name: 'Meat on bone' },
      { emoji: '🌭', name: 'Hot dog' },
      { emoji: '🍔', name: 'Hamburger' },
      { emoji: '🍟', name: 'French fries' },
      { emoji: '🍕', name: 'Pizza' },
      { emoji: '🫓', name: 'Flatbread' },
      { emoji: '🥪', name: 'Sandwich' },
      { emoji: '🥙', name: 'Stuffed flatbread' },
      { emoji: '🧆', name: 'Falafel' },
      { emoji: '🌮', name: 'Taco' },
      { emoji: '🌯', name: 'Burrito' },
      { emoji: '🫔', name: 'Tamale' },
      { emoji: '🥗', name: 'Green salad' },
      { emoji: '🥘', name: 'Shallow pan of food' },
      { emoji: '🫕', name: 'Fondue' },
      { emoji: '🥫', name: 'Canned food' },
      { emoji: '🍝', name: 'Spaghetti' },
      { emoji: '🍜', name: 'Steaming bowl' },
      { emoji: '🍲', name: 'Pot of food' },
      { emoji: '🍛', name: 'Curry rice' },
      { emoji: '🍣', name: 'Sushi' },
      { emoji: '🍱', name: 'Bento box' },
      { emoji: '🥟', name: 'Dumpling' },
      { emoji: '🦪', name: 'Oyster' },
      { emoji: '🍤', name: 'Fried shrimp' },
      { emoji: '🍙', name: 'Rice ball' },
      { emoji: '🍚', name: 'Cooked rice' },
      { emoji: '🍘', name: 'Rice cracker' },
      { emoji: '🍥', name: 'Fish cake with swirl' },
      { emoji: '🥠', name: 'Fortune cookie' },
      { emoji: '🥮', name: 'Mooncake' },
      { emoji: '🍢', name: 'Oden' },
      { emoji: '🍡', name: 'Dango' },
      { emoji: '🍧', name: 'Shaved ice' },
      { emoji: '🍨', name: 'Ice cream' },
      { emoji: '🍦', name: 'Soft ice cream' },
      { emoji: '🥧', name: 'Pie' },
      { emoji: '🧁', name: 'Cupcake' },
      { emoji: '🍰', name: 'Shortcake' },
      { emoji: '🎂', name: 'Birthday cake' },
      { emoji: '🍮', name: 'Custard' },
      { emoji: '🍭', name: 'Lollipop' },
      { emoji: '🍬', name: 'Candy' },
      { emoji: '🍫', name: 'Chocolate bar' },
      { emoji: '🍿', name: 'Popcorn' },
      { emoji: '🍩', name: 'Doughnut' },
      { emoji: '🍪', name: 'Cookie' },
      { emoji: '🌰', name: 'Chestnut' },
      { emoji: '🥜', name: 'Peanuts' },
      { emoji: '🍯', name: 'Honey pot' },
      { emoji: '🥛', name: 'Glass of milk' },
      { emoji: '🍼', name: 'Baby bottle' },
      { emoji: '🫖', name: 'Teapot' },
      { emoji: '☕', name: 'Hot beverage' },
      { emoji: '🍵', name: 'Teacup without handle' },
      { emoji: '🧃', name: 'Beverage box' },
      { emoji: '🥤', name: 'Cup with straw' },
      { emoji: '🧋', name: 'Bubble tea' },
      { emoji: '🍶', name: 'Sake' },
      { emoji: '🍺', name: 'Beer mug' },
      { emoji: '🍻', name: 'Clinking beer mugs' },
      { emoji: '🥂', name: 'Clinking glasses' },
      { emoji: '🍷', name: 'Wine glass' },
      { emoji: '🥃', name: 'Tumbler glass' },
      { emoji: '🍸', name: 'Cocktail glass' },
      { emoji: '🍹', name: 'Tropical drink' },
      { emoji: '🧉', name: 'Mate' },
      { emoji: '🍾', name: 'Bottle with popping cork' },
      { emoji: '🧊', name: 'Ice' },
      { emoji: '🥄', name: 'Spoon' },
      { emoji: '🍴', name: 'Fork and knife' },
      { emoji: '🍽️', name: 'Fork and knife with plate' },
      { emoji: '🥣', name: 'Bowl with spoon' },
      { emoji: '🥡', name: 'Takeout box' },
      { emoji: '🥢', name: 'Chopsticks' },
      { emoji: '🧂', name: 'Salt' },
    ]
  },
  {
    name: 'Activities & Objects',
    icon: 'Activity',
    emojis: [
      { emoji: '⚽', name: 'Soccer ball' },
      { emoji: '🏀', name: 'Basketball' },
      { emoji: '🏈', name: 'American football' },
      { emoji: '⚾', name: 'Baseball' },
      { emoji: '🥎', name: 'Softball' },
      { emoji: '🎾', name: 'Tennis' },
      { emoji: '🏐', name: 'Volleyball' },
      { emoji: '🏉', name: 'Rugby football' },
      { emoji: '🥏', name: 'Flying disc' },
      { emoji: '🎱', name: 'Pool 8 ball' },
      { emoji: '🪀', name: 'Yo-yo' },
      { emoji: '🏓', name: 'Ping pong' },
      { emoji: '🏸', name: 'Badminton' },
      { emoji: '🏒', name: 'Ice hockey' },
      { emoji: '🏑', name: 'Field hockey' },
      { emoji: '🥍', name: 'Lacrosse' },
      { emoji: '🏏', name: 'Cricket game' },
      { emoji: '🪃', name: 'Boomerang' },
      { emoji: '🥅', name: 'Goal net' },
      { emoji: '⛳', name: 'Flag in hole' },
      { emoji: '🪁', name: 'Kite' },
      { emoji: '🏹', name: 'Bow and arrow' },
      { emoji: '🎣', name: 'Fishing pole' },
      { emoji: '🤿', name: 'Diving mask' },
      { emoji: '🥊', name: 'Boxing glove' },
      { emoji: '🥋', name: 'Martial arts uniform' },
      { emoji: '🎽', name: 'Running shirt' },
      { emoji: '🛹', name: 'Skateboard' },
      { emoji: '🛼', name: 'Roller skate' },
      { emoji: '🛷', name: 'Sled' },
      { emoji: '⛸️', name: 'Ice skate' },
      { emoji: '🥌', name: 'Curling stone' },
      { emoji: '🎿', name: 'Skis' },
      { emoji: '⛷️', name: 'Skier' },
      { emoji: '🏂', name: 'Snowboarder' },
      { emoji: '🪂', name: 'Parachute' },
      { emoji: '🏋️', name: 'Person lifting weights' },
      { emoji: '🤼', name: 'People wrestling' },
      { emoji: '🤸', name: 'Person cartwheeling' },
      { emoji: '⛹️', name: 'Person bouncing ball' },
      { emoji: '🤺', name: 'Person fencing' },
      { emoji: '🤾', name: 'Person playing handball' },
      { emoji: '🏌️', name: 'Person golfing' },
      { emoji: '🏇', name: 'Horse racing' },
      { emoji: '🧘', name: 'Person in lotus position' },
      { emoji: '🏄', name: 'Person surfing' },
      { emoji: '🏊', name: 'Person swimming' },
      { emoji: '🤽', name: 'Person playing water polo' },
      { emoji: '🚣', name: 'Person rowing boat' },
      { emoji: '🧗', name: 'Person climbing' },
      { emoji: '🚵', name: 'Person mountain biking' },
      { emoji: '🚴', name: 'Person biking' },
      { emoji: '🏆', name: 'Trophy' },
      { emoji: '🥇', name: '1st place medal' },
      { emoji: '🥈', name: '2nd place medal' },
      { emoji: '🥉', name: '3rd place medal' },
      { emoji: '🏅', name: 'Sports medal' },
      { emoji: '🎖️', name: 'Military medal' },
      { emoji: '🏵️', name: 'Rosette' },
      { emoji: '🎗️', name: 'Reminder ribbon' },
      { emoji: '🎫', name: 'Ticket' },
      { emoji: '🎟️', name: 'Admission tickets' },
      { emoji: '🎪', name: 'Circus tent' },
      { emoji: '🤹', name: 'Person juggling' },
      { emoji: '🎭', name: 'Performing arts' },
      { emoji: '🩰', name: 'Ballet shoes' },
      { emoji: '🎨', name: 'Artist palette' },
      { emoji: '🎬', name: 'Clapper board' },
      { emoji: '🎤', name: 'Microphone' },
      { emoji: '🎧', name: 'Headphone' },
      { emoji: '🎼', name: 'Musical score' },
      { emoji: '🎹', name: 'Musical keyboard' },
      { emoji: '🥁', name: 'Drum' },
      { emoji: '🪘', name: 'Long drum' },
      { emoji: '🎷', name: 'Saxophone' },
      { emoji: '🎺', name: 'Trumpet' },
      { emoji: '🪗', name: 'Accordion' },
      { emoji: '🎸', name: 'Guitar' },
      { emoji: '🪕', name: 'Banjo' },
      { emoji: '🎻', name: 'Violin' },
      { emoji: '🎲', name: 'Game die' },
      { emoji: '♟️', name: 'Chess pawn' },
      { emoji: '🎯', name: 'Direct hit' },
      { emoji: '🎳', name: 'Bowling' },
      { emoji: '🎮', name: 'Video game' },
      { emoji: '🎰', name: 'Slot machine' },
      { emoji: '🧩', name: 'Puzzle piece' },
    ]
  }
];

export const lottieData = [
  { id: '1', name: 'Sticker 1', source: require('../../../assets/stickers/sticker_1.json') },
  { id: '2', name: 'Sticker 2', source: require('../../../assets/stickers/sticker_2.json') },
  { id: '3', name: 'Sticker 3', source: require('../../../assets/stickers/sticker_3.json') },
  { id: '4', name: 'Sticker 4', source: require('../../../assets/stickers/sticker_4.json') },
  { id: '5', name: 'Sticker 5', source: require('../../../assets/stickers/sticker_5.json') },
  { id: '6', name: 'Sticker 6', source: require('../../../assets/stickers/sticker_6.json') },
  { id: '7', name: 'Sticker 7', source: require('../../../assets/stickers/sticker_7.json') },
  { id: '8', name: 'Sticker 8', source: require('../../../assets/stickers/sticker_8.json') },
];
